import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { Metadata } from "next";
import { Bot, FileText, Globe, Shield, Zap } from "lucide-react";
import { DynamicMenu } from "@/components/dynamic-menu";
import { getFileContent, getRepoFiles } from "@/lib/github";
import { generateHomepageContent } from "@/ai/flows/homepage-content-generation";
import { Storage } from "@google-cloud/storage";
import type { HomepageContentOutput } from "@/ai/schemas/homepage-content-schema";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Github } from "lucide-react";
import { ComponentType } from "react";
import Logo from "@/components/logo";

const iconMap: { [key: string]: ComponentType<{ className?: string }> } = {
  FileText,
  Zap,
  Shield,
  Globe,
  Bot,
};

// Generate dynamic metadata based on AI-generated content
export async function generateMetadata(): Promise<Metadata> {
  const homepageContent = await getHomepageContent();

  const title =
    homepageContent?.title || "Seon | AI-Powered Documentation Platform";
  const description =
    homepageContent?.sections?.[0]?.content ||
    "Discover and explore documentation with AI-powered navigation. Transform GitHub repositories into intelligent, searchable knowledge bases with dynamic content generation.";

  const keywords = [
    "AI documentation",
    "intelligent search",
    "markdown explorer",
    "GitHub integration",
    "knowledge management",
    "content discovery",
    ...(homepageContent?.sections?.map((s) => s.title.toLowerCase()) || []),
  ];

  const baseUrl =
    process.env.NEXT_PUBLIC_BASE_URL || "https://theseonproject.com";

  return {
    title,
    description: description.slice(0, 160),
    keywords,
    openGraph: {
      title,
      description: description.slice(0, 160),
      url: baseUrl,
      type: "website",
      siteName: "Seon",
      images: [
        {
          url: "/og-image.png",
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: description.slice(0, 160),
      images: ["/og-image.png"],
    },
    alternates: {
      canonical: "/",
    },
  };
}

async function getHomepageContent(): Promise<HomepageContentOutput | null> {
  try {
    const bucketName =
      process.env.GCS_BUCKET || process.env.FIREBASE_STORAGE_BUCKET;
    const objectPath = "generated/homepage-content.json";

    if (bucketName) {
      const storage = new Storage();
      const bucket = storage.bucket(bucketName);
      const file = bucket.file(objectPath);

      // check if object exists
      try {
        const [exists] = await file.exists();
        if (exists) {
          const [contents] = await file.download();
          return JSON.parse(
            contents.toString("utf-8")
          ) as HomepageContentOutput;
        }
      } catch (e) {
        console.error("Failed to read from GCS:", e);
        // fallthrough to generate
      }
    }

    const whitepaperContent = await getFileContent("Whitepaper.md");
    if (!whitepaperContent) return null;

    // Only attempt generation if an API key is available at runtime
    if (!process.env.GEMINI_API_KEY && !process.env.GOOGLE_API_KEY) {
      console.warn(
        "Skipping homepage generation: missing GEMINI_API_KEY/GOOGLE_API_KEY"
      );
      return null;
    }

    const generated = await generateHomepageContent({ whitepaperContent });

    // persist to GCS if bucket configured
    if (bucketName) {
      try {
        const storage = new Storage();
        const bucket = storage.bucket(bucketName);
        const file = bucket.file(objectPath);
        await file.save(JSON.stringify(generated, null, 2), {
          resumable: false,
          contentType: "application/json",
        });
      } catch (e) {
        console.error("Failed to write generated homepage content to GCS:", e);
      }
    }

    return generated;
  } catch (error) {
    console.error("Failed to generate homepage content:", error);
    return null;
  }
}

export default async function Home() {
  const files = await getRepoFiles();
  const homepageContent = await getHomepageContent();

  return (
    <div className="mx-auto max-w-5xl px-4">
      <div className="flex flex-col items-center justify-center space-y-4 text-center py-16">
        <div className="flex items-center gap-4">
          <Logo className="size-16 text-primary" ariaHidden={true} />
          <h1 className="text-4xl md:text-5xl font-bold font-headline tracking-tighter">
            {homepageContent?.title || "Welcome to Seon"}
          </h1>
        </div>
        <p className="max-w-3xl text-lg text-muted-foreground">
          This page was generated by an AI assistant that analysed the project's{" "}
          <Link href="/Whitepaper.md" className="text-primary hover:underline">
            white paper
          </Link>
          . Use the AI-powered search below to find what you're looking for.
        </p>
        <div className="mt-6">
          <Link href="/Whitepaper.md" aria-label="Read the Seon white paper">
            <Button variant="inverted" size="lg" className="w-full md:w-auto">
              <Github />
              Read the Seon white paper
            </Button>
          </Link>
        </div>
      </div>

      <div className="space-y-16 py-12">
        {homepageContent ? (
          homepageContent.sections.map((section, index) => {
            const Icon = iconMap[section.icon] || FileText;
            return (
              <section key={index} className="max-w-3xl mx-auto px-4">
                <div className="flex items-center gap-3">
                  <Icon className="size-8 text-primary" />
                  <h2 className="text-3xl font-bold font-headline">
                    {section.title}
                  </h2>
                </div>
                <p className="mt-4 text-lg text-muted-foreground">
                  {section.content}
                </p>
              </section>
            );
          })
        ) : (
          <Card className="md:col-span-2 lg:col-span-3">
            <CardHeader>
              <CardTitle>Welcome</CardTitle>
            </CardHeader>
            <CardContent>
              <p>Explore the documentation using the menu.</p>
            </CardContent>
          </Card>
        )}
      </div>

      <Card className="mt-12 mb-16 max-w-2xl mx-auto">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 font-headline">
            <Bot className="text-primary" />
            AI-Powered Search
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground mb-4">
            Leverages a GenAI model to create a dynamic navigation menu based on
            your search query.
          </p>
          <DynamicMenu allFiles={files} />
        </CardContent>
      </Card>
    </div>
  );
}
